version: '3.9'

services:
  go_app:
    container_name: go_app
    image: go-api
    build: .
    ports:
      - "8083:8080"
    depends_on:
      - go_db
  go_db:
    image: postgres:12
    container_name: go_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: